version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fit3164-dashboard:latest
    container_name: fit3164_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/weatherdb
      - API_HOST=0.0.0.0
      - API_PORT=8000
    depends_on:
      - postgres
    volumes:
      - ./config:/app/config:ro
      - ./frontend:/app/frontend:ro
